// <auto-generated />
using System;
using Collage_MVC;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CollageMVC.Migrations
{
    [DbContext(typeof(MyAppDataContext))]
    [Migration("20221109100213_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Collage_MVC.Models.Club", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Club_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("Collage_MVC.Models.Course", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Course_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Collage_MVC.Models.Student", b =>
                {
                    b.Property<int>("Student_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Student_Id"));

                    b.Property<int?>("Clubid")
                        .HasColumnType("int");

                    b.Property<int?>("Courseid")
                        .HasColumnType("int");

                    b.Property<string>("Student_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Student_dob")
                        .HasColumnType("datetime2");

                    b.HasKey("Student_Id");

                    b.HasIndex("Clubid");

                    b.HasIndex("Courseid");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Collage_MVC.Models.Student", b =>
                {
                    b.HasOne("Collage_MVC.Models.Club", null)
                        .WithMany("Students")
                        .HasForeignKey("Clubid");

                    b.HasOne("Collage_MVC.Models.Course", null)
                        .WithMany("Students")
                        .HasForeignKey("Courseid");
                });

            modelBuilder.Entity("Collage_MVC.Models.Club", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Collage_MVC.Models.Course", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
